### ISSUE TITLE
Fee suggestion : Use high priority unless higher than x$ or x% of amount sent.

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#278]
For example

If I'm sending 10$ worth I would not want the fee to be higher than 1.5%, or $0.15 worth.

If I'm sending 5000$ I would want to use high priority unless the it cost more than 1$ worth.

I'm seriously fed up with using "normal" fee and not have my transaction confirmed for 24 hours because the block discovery rate changed afterward.

Before you implement RFB, that would be extremely useful.

**Comment by Giszmo** [comment]
Well, the fee control is guesswork but Mycelium gives you the best estimate available on when it will confirm for a given price. The longer you are willing to wait, the higher the insecurity, as the situation can change and there is no waiting bonus.

So your feature request is to do what exactly? Default to priority but if that's too expensive, switch to wait longer without warning? Or limit the amount, still claiming it was the higher priority? Or show a modal alert to confirm the high price?

I tend to close this as "won't fix" but if you could elaborate how you would want the UI to look and work, then maybe we can make something of it.

**Comment by Transisto** [comment]
First I think the UI should explain more what to expect from a transaction fee of Normal, High and Economic.

The only information given is when using Economic it write "Might take longer to confirm"

What I was personally expecting was Normal = 90% chances of being on the next block.
And High was 99.9% chance to be in the next block.

I have read somewhere that with normal we should expect to be in the next 3 block, That should be made clear.  If not having a ? icon that just pop-up a explanation of what to expect.

It's very important that people are not disappointed with the use of the wallet. "Normal" used to be find but lately have been sometime waiting a day to get my transaction through.

One way I would see the UI would be to have another fee level called "Custom". Which rules would be found in the settings. I think the setting could also have a fee protection, my understanding is that you are fetching the fee though some external service that could get compromised and people get used to sending transaction without checking the fee.

I would personally keep my fee at high priority if I knew there was a high fee warning at 1$ worth.

**Comment by Giszmo** [comment]
`Normal` taking a day was a bug that is fixed now since two days.

The promises of x% chance of getting confirmed after y blocks would be good and it would be good to keep this information visible in the transaction list, as it can get worse over time. People expect to get some waiting bonus like as if waiting was a punishment for not paying more.

The "external service" we fetch the fees from, is a bitcoind run on our servers.

**Comment by Transisto** [comment]
Do updates only get pushed to the play store on week days ? My last Mycelium update is from Jun 2

**Comment by Giszmo** [comment]
@DanielWeigl, could you please set the releas to 100%. It's still at 50% and seams to be fine.

**Comment by DanielWeigl** [comment]
> could you please set the release to 100%
done

**Comment by Perlover** [comment]
Hi,

Thanks for fixing!
But now there is other problem :)

Normal comission now is very high (i see about 50 satoshi/byte) - more than middle fee of current pool. For example i see at TradeBlock.com current pool as 2-3 Mb only and there is average fee as 40-50 satoshi/byte.

The Mycelium's economic comission now is as normal fee what should be used for current mempool market. It's my opinion of course

Please see here:

https://tradeblock.com/bitcoin/

Click there "Recent Mempool" -> please choose "Fee/Size"
There Yesterday were 10-20 satoshi/byte average and pool about 2-3 Mb (normal pool without spam/mixer transactions) but after Mycelium relesae 2.8.3 (was released 26.6.2016) when this bug was fixed i see constantly high middle average fees during day: 40-50 satoshi/byte

My theory is that the many people use the Mycelium and after upgrade the fee market of Bitcoin was increased by Mycelum release. Now i see that fee market is going slow to down but may be it occurs because now there are many low-fee transactions (spam? now i see 6Mb pool). But i hope if there will not be spam transaction there will be 40-50 fee again and main reason - release v2.8.3 of Mycelum. 

What do you think? :)

**Comment by Perlover** [comment]
And i only about that how a current software of bitcoin wallet can affect to fee market. If there (bitcoin mempool) are many transactions - it's good for Mycelium users (transaction will be confirmed in first blocks) but if there no spam transactions and the mempool of Bitcoin is 2-3Mb only i think fee as 40-50 satoshi/byte as normal is very high. For European/USA people it can be not high but for Africans people this comission is very high (for example simple 225 byte transaction will cost 7 cents).

**Comment by Perlover** [comment]
Yesterday i made three transactions (the mempool of bitcoin was about 2Mb) from Mycelium 2.8.3 (fixed this bug): normal, economic and low-priority. And  all three transactions were confirmed in first block...

**Comment by Giszmo** [comment]
@DanielWeigl the bug about too low fees was just remotely interfering with this issue which is about some limits on top of the dynamic fees. "Pay high priority if it's cheap, else warn me". I think that one is not resolved yet. On the other hand I doubt we will solve it, as I can't see well, how. (suggestions with patches welcome)

@Perlover the fees are dynamic and average fees and mempool size are not the primary drivers of the fee. With 12GB of mempool, with an average of 3sat/B, it might still be possible to get next block confirmation with 9sat/B if all but a few kB of the mempool was lower than 9sat/B. Mycelium uses the bitcoincore fee estimations.
