### ISSUE TITLE
No Local Trader Notifications

### ISSUE THREAD

**Issue by puggan** [mycelium-com/wallet#77]
I'd like to get some kind of notice when a trader starts a trade, and tries to communicate with me. I guess you have build some kind of notification, that doesn't work on my phone.
The settings have an option for "Play sound on Trade activity", the result from having that active (on my phone) is that i hear a sound, if i start mycelium, and open "Buy /Sell bitcoins", even if the activeity was a few days ago, the first notice i get is when i click the button "Buy /Sell bitcoins".
(It's hard to trade if someone at Friday ask to meet up in the weekend, and I read it on Monday)

How dose it works on other phones?
Is there some things i can test, to make it easier for you to find why It works diferent on my phone?

Mycelium: 1.2.2
Android: 2.3.7
Phone: Sony Experia  ST27i

**Comment by raedah** [comment]
I have this issue as well, and its been constant since, yeah, back in May or so.

**Comment by DanielWeigl** [comment]
The notification system depends on google-services and it seems it does not work under certain circumstances (we never were able to reliable reproduce it on our own) - so we implemented an optional notification via email: Go to Settings and set the Localtrader-notifcation Mail address.

**Comment by raedah** [comment]
No offense, but resorting to email is quite a hack of a work around. Did you try running Mycelium Wallet on a phone with CyanogenMod?

**Comment by Giszmo** [comment]
Can we close this in favor of #162 ?

**Comment by raedah** [comment]
@Giszmo What if #162 is closed later as 'not going to do'?  Then what?

I did some testing on this issue and it seems there is a correlation to notification not working only when Mycelium is going through Tor. Currently I have Orbot support disabled, and the notifications are again working properly.

**Comment by Giszmo** [comment]
Sorry, @raedah you are right. This is not an issue of "I don't have google" but of "I have google but it still doesn't work at times".

Thank you for the TOR pointer. We will have to try that.
